# Generated by Django 5.0.1 on 2025-11-10 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('other', 'Other')], max_length=20)),
                ('registration_date', models.DateField()),
                ('region', models.CharField(choices=[('urban', 'Urban'), ('peri_urban', 'Peri-Urban'), ('rural', 'Rural')], max_length=20)),
                ('last_license_renewal', models.DateField(blank=True, null=True)),
                ('is_currently_licensed', models.BooleanField(default=False)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('preferred_payment_mode', models.CharField(choices=[('online', 'Online'), ('mobile_money', 'Mobile Money'), ('agent', 'Agent'), ('cash', 'Cash')], max_length=20)),
                ('total_renewals', models.IntegerField(default=0)),
                ('late_renewals_count', models.IntegerField(default=0)),
                ('average_renewal_delay', models.FloatField(default=0.0)),
                ('last_agent_sync', models.DateTimeField(blank=True, null=True)),
                ('agent_sync_delay', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('predicted_unlicensed', models.BooleanField(blank=True, null=True)),
                ('last_prediction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('records_count', models.IntegerField(default=0)),
                ('processing_notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_uploads',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField()),
                ('predicted_unlicensed', models.BooleanField()),
                ('model_version', models.CharField(max_length=20)),
                ('features_used', models.JSONField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.vehiclerecord')),
            ],
            options={
                'db_table': 'prediction_logs',
                'ordering': ['-prediction_date'],
            },
        ),
    ]
