# Generated by Django 5.0.1 on 2025-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='confusion_matrix',
            field=models.JSONField(blank=True, help_text='Confusion matrix: [[TN, FP], [FN, TP]]', null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='threshold',
            field=models.FloatField(blank=True, help_text='Optimal threshold for predictions', null=True),
        ),
    ]
